### ISSUE TITLE
How do I use the bin/project* scripts?

### ISSUE THREAD

**Issue by certa1n** [sunaku/home#2]
Hello.
Possible a small instructions abou use your any scripts? 

project-release-notes
project-version-commit
project-version-update
git-tag-versions

Thank you!

**Comment by sunaku** [comment]
Sure, I use those project-* scripts to generate release notes for my [md2man](https://github.com/sunaku/md2man), [binman](https://github.com/sunaku/binman), [tork](https://github.com/sunaku/tork), and [dasht](https://github.com/sunaku/dasht) projects.  Let's take the latter as an example:

1.  Clone [dasht](https://github.com/sunaku/dasht):

        git clone https://github.com/sunaku/dasht.git
        cd dasht/

2.  Preview the release notes for the upcoming release:

        project-release-notes VERSION.md

3.  Insert the new release notes at the top of the history file (`VERSION.md` in this case):

        vim VERSION.md
        :0r! project-release-notes %
        :wq

4.  Update all mentions of the old release to the new release:

        project-version-update VERSION.md

5.  Inspect the changes and stage them for committing if correct:

        git diff   # inspect the changes
        git add -u # stage the changes for committing

6.  Commit the new release:

        project-version-commit VERSION.md

7.  You can now publish the new release whenever you're ready:

        git push
        git push --tags

**Comment by certa1n** [comment]
Thank you!

**Comment by sunaku** [comment]
Note that I renamed all of these scripts to `floss-*` in commit fa687eff22857a5ba1de0d44a19bfe878a4a4487, as follows:

* [floss-rebase]( https://github.com/sunaku/home/blob/master/bin/floss-rebase ):
  Reapplies the stacked branch architecture:
  master => other => patch => minor => major

* [floss-merge]( https://github.com/sunaku/home/blob/master/bin/floss-merge ):
  Merges all branches up to and including current branch into master branch.

* [floss-changes]( https://github.com/sunaku/home/blob/master/bin/floss-changes ):
  Prints release notes ranging from the current branch to the master branch.

* [floss-reflect]( https://github.com/sunaku/home/blob/master/bin/floss-reflect ):
  Updates all text files in the project that mention the current version
  and/or date to match the first version and date from the HISTORY_FILE.

* [floss-commit]( https://github.com/sunaku/home/blob/master/bin/floss-commit ):
  Creates a new commit or updates an existing commit that is labelled with
  the first version and date from the HISTORY_FILE.

* [floss-publish]( https://github.com/sunaku/home/blob/master/bin/floss-publish ):
  Publishes manuals to the GitHub pages website after a project release.
