### ISSUE TITLE
Async update git info?

### ISSUE THREAD

**Issue by tmpm697** [sunaku/home#3]
https://github.com/sunaku/home/blob/68c5c638df4857f0d09a2c93f744655b6ee389e1/.zsh/config/prompt.zsh#L35

Sorin promt from prezto use async to do git and it faster than your config (~0.01 - 0.03s), Is there a way to mitigrate your current setup to use async?

> https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup

**Comment by sunaku** [comment]
Yes, it should be possible to make `vcs_info` asynchronous:
https://vincent.bernat.ch/en/blog/2019-zsh-async-vcs-info

**Comment by sunaku** [comment]
Solved in commit 9df73407e54ffc706039bb8caff1532be2068b43. :neckbeard:  Thanks for suggesting this. :+1:
